import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for task.coop.',
}

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-14 prose prose-stone">
      <h1>Privacy Policy</h1>
      <p className="text-stone-500 text-sm">Last updated: May 2026</p>

      <h2>1. Information We Collect</h2>
      <p>We collect information you provide directly (name, email, profile details), information generated by your use of the platform (tasks posted, offers submitted, messages), and payment information processed by Stripe (we never store full card numbers).</p>

      <h2>2. How We Use Your Information</h2>
      <p>We use your information to operate the platform, facilitate transactions, send you notifications about your account and tasks, and improve our services.</p>

      <h2>3. Information Sharing</h2>
      <p>We do not sell your personal information. We share information with Stripe for payment processing. We may share information when required by law.</p>
      <p>Your public profile (name, bio, ratings) is visible to all users. Task details are visible to all users.</p>

      <h2>4. Cookies</h2>
      <p>We use cookies for authentication (Supabase session management). We do not use third-party advertising cookies.</p>

      <h2>5. Data Retention</h2>
      <p>We retain your data as long as your account is active. You may request deletion of your account by emailing us.</p>

      <h2>6. Security</h2>
      <p>We use industry-standard security measures. Passwords are hashed. Payment data is handled by Stripe's PCI-compliant infrastructure.</p>

      <h2>7. Your Rights</h2>
      <p>You may access, correct, or delete your personal information by contacting us or through your profile settings.</p>

      <h2>Contact</h2>
      <p>Privacy questions: <a href="mailto:privacy@task.coop">privacy@task.coop</a>.</p>
    </div>
  )
}
